apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbvol-1
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw
    server: k8scp   #<-- Edit to match cp node
    readOnly: false
